Track project owner - Jose and Najib
1810-oct08-java-usf/project-service pull request #140
Opened 2019-08-05 19:51 UTC by jose2a

Change files:
ProjectController.java
ProjectDTO.java
ProjectService.java
ProjectControllerTestSuite.java

Added userId to project that way we know who submitted it

2019-08-05 20:20 UTC, jose2a commented
Fixed tests and removed workaround

2019-08-06 18:31 UTC, jurczakn requested changes

2019-08-06 18:31 UTC, jurczakn commented on src/test/java/com/revature/controllers/CreateProjecIntegrationTest.java
>  						.param("techStack", "techStack")
Can you please change the name of this test file.

2019-08-06 18:46 UTC, jurczakn approved these changes
Good, file name changed

2019-08-06 18:48 UTC, merged