submitEditRequest method added. test added.
1810-oct08-java-usf/project-service pull request #143
Opened 2019-08-07 20:54 UTC by ahodge10

Submit edit request functionality complete. Testing added in testing class.

2019-08-09 18:21 UTC, jurczakn requested changes

2019-08-09 18:21 UTC, jurczakn commented on src/main/java/com/revature/services/ProjectService.java
> +//            System.out.println(project.getOldProject().getBatch());
Remove commented out code

2019-08-09 20:14 UTC, ahodge10 commented
Requested changes completed.

2019-08-12 14:38 UTC, jurczakn requested changes

2019-08-12 14:38 UTC, jurczakn commented on src/main/java/com/revature/security/CustomAuthenticationFilter.java
> +			// throw new RuntimeException(ipAddress + " " + appUrl, e);
still has commented out code

2019-08-12 14:38 UTC, jurczakn commented on src/main/java/com/revature/security/CustomAuthenticationFilter.java
> +			System.out.println("URL     " + appUrl);
still has sys out

2019-08-13 18:25 UTC, ahodge10 commented
CustomAuthenticationFilter and tests updated to pass Jenkins build

2019-08-13 19:27 UTC, jurczakn approved these changes
ok

2019-08-13 19:27 UTC, merged